server:
  port: 9006

spring:
  application:
    name: CONSENT-MANAGER-SERVICE

  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/ConsentManager
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Tripathi}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

