server:
  port: 9006

spring:
  application:
    name: CONSENT-MANAGER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/ConsentManager
    username: root
    password: Tripathi
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka
    instance:
      hostname: localhost