server:
  port: 9002

spring:
  application:
    name: HOSPITAL-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/HospitalA
    username: root
    password: lalith

  jpa:
    hibernate:
      ddl-auto: update

