server:
  port: 9005

spring:
  application:
    name: GATEWAY-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/swaksha
    username: root
    password: lalith
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka
    instance:
      hostname: localhost
